<a href="https://colab.research.google.com/github/Dymphie81/Numpy_Pandas_Matplotlib_Documentation/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#To check the numpy version
import numpy as np
print(np.__version__)

1.23.5


In [ ]:
#To print array and check the array type
arr = np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [ ]:
#To use a tuple to create a Numpy array

arr = np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [ ]:
# creating an array using np.zeros
# create an array with 5 elements filled with zeros

arr1 = np.zeros(5)
print(arr1)
# To create an array filled with ones

arr2 = np.ones(4)
print(arr2)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1.]


In [ ]:
# create an array with np.arange
# create an array with values from zero to four
arr1 = np.arange(5)
print(arr1)

# create an array with values from 1 to 8 with a step of 2
arr2 = np.arange(1,9,2)
print(arr2)

[0 1 2 3 4]
[1 3 5 7]


In [ ]:
# create an array with np.random.rand()
# generate an array of 5 random numbers
arr1 = np.random.rand(5)
print(arr1)




[0.13010947 0.20581095 0.7076502  0.29116602 0.68337034]


In [ ]:
# create an empty numpy array

arr = np.empty(5)
print(arr)

[0.0e+000 4.9e-324 9.9e-324 1.5e-323 2.0e-323]


In [ ]:
# create a 0-D array, ndim tells you how many dimension the array has

arr = np.array(20)
print(arr)
print(arr.ndim)

20
0


In [ ]:
#create a 1-D array

arr = np.array([1,7,8])
print(arr, arr.ndim)

[1 7 8] 1


In [ ]:
#create a 2-D array

arr = np.array([[1,7,8],[2,4,6]])

print(arr, arr.ndim)

[[1 7 8]
 [2 4 6]] 2


In [ ]:
# create a 3-D array

arr = np.array([[[1,2,3,4],[4,5,6,7]],[[8,9,10,11],[12,13,14,15]]])

print(arr, arr.ndim)

[[[ 1  2  3  4]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] 3


In [ ]:
# array indexing

arr1 = ([1,3,4,7])
print(arr1[0])
print(arr1[2], arr1[3])

1
4 7


In [ ]:
#Indexing 2-D arrays

arry = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print('3rd column element on the 1st row: ', arry[0,2])

#Indexing 2-D arrays

Myarray = np.array([['My', 'mum', 'is'],['the', 'sweetest','soul'],['I','have','ever'],['come','across','love']])

print(f"{Myarray[0,1]} and {Myarray[1,2]} ever love")

3rd column element on the 1st row:  3
mum and soul ever love


In [ ]:
# Indexing 3-D arrays

arr3 = np.array([[[1,2,4,6],[3,9,12,7]],[[10,11,8,6],[12,14,18,20]]])

print("First 2-D array, Second 1-D array, Second element is",arr3[0,1,1])

First 2-D array, Second 1-D array, Second element is 9


In [ ]:
#Negative Indexing

arr1 = np.array([1,2,3,4])
print("Last element from 1st dimension", arr1[-1])

arr2 = np.array([['who', 'is', 'in'],['the', 'garden', 'a']])
print("The last element from the 1st dimension", arr2[1,-1])

arr3 = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print("The last element from the 3rd dimension", arr3[0,1,-3])


Last element from 1st dimension 4
The last element from the 1st dimension a
The last element from the 3rd dimension 6


In [ ]:
# Modifying elements

# changing the value of elements in an array

arr1 = np.array([1,2,3,4])
#Change the value of the first element
arr1[0] = 5
print("After modifying the first element", arr1)

#Change the value of the 4th element
arr1[3] = 10
print("After modifying the 4th element", arr1)

#Modifying Array Elements using Negative Indexing

elements = np.array([2,4,6,8])

#Change the value of the last element
elements[-1] = 10
print("After modifying the last element", elements)

#Change the third to last element
elements[-3] = 8

print("After modifying the Third to last element", elements)


After modifying the first element [5 2 3 4]
After modifying the 4th element [ 5  2  3 10]
After modifying the last element [ 2  4  6 10]
After modifying the Third to last element [ 2  8  6 10]


In [ ]:
#Array Slicing
arr1 =np.array([1,2,3,4,5,6])

#Slice array1 from index 1 to index 4
print(arr1[1:4])

#Create a number array
arr2 = np.array([1,2,3,4,5,6,7,8,9])

#Slice array from index 4 to the end
print(arr2[4:])
#Slice array from beginning to index 4
print(arr2[:4])
#Slice array using the negative index
print(arr2[-4:-1])

[2 3 4]
[5 6 7 8 9]
[1 2 3 4]
[6 7 8]


In [ ]:
#Step Slicing
arr1 = np.array([1,2,3,4,5,6,7,8,9])
#Return every other element from Index 0 to 5
print(arr1[0:5:2])

# Return every other element from the entire array
print(arr1[::2])

#Slicing 2-D arrays
arr2 = np.array([[1,2,3,4],[5,6,7,8,]])

print(arr2[1, 2:5])

#from both elements return index 2
print(arr2[0:2, 2])

#Modifying array elements using slicing

# create a numpy array
numbers = np.array([2, 4, 6, 8, 10, 12])

# modify elements from index 3 onwards
numbers[3:] = 20
print(numbers)

#Reverse array using negative indexing
print(numbers[::-1])



[1 3 5]
[1 3 5 7 9]
[7 8]
[3 7]
[ 2  4  6 20 20 20]
[20 20 20  6  4  2]


In [ ]:
# Checking Data Types
arr = np.array([1,2,3,4,5,6])
print([arr. dtype])

# create an array of floating-point numbers
float_array = np.array([0.1, 0.2, 0.3])

# create an array of complex numbers
complex_array = np.array([1+2j, 2+3j, 3+4j])

# create an array of strings
string_array = np.array(['who','are','you ?'])

# check the data type of float_array
print(float_array.dtype)

# check the data type of complex_array
print(complex_array.dtype)

# check the data type of string_array
print(string_array.dtype)

# Creating arrays with defined data types

#create an array with data type string
arr1 = np.array([2, 4, 6, 8], dtype='S')

# create an array of unsigned 16-bit integers
arr2 = np.array([1, 2, 6], dtype='uint16')

# create an array of 32-bit floating-point numbers
arr3 = np.array([1.4, 2.5, 3.8], dtype='float32')

# create an array of 64-bit complex numbers
arr4 = np.array([1+8j, 2+3j, 3+5j], dtype='complex64')

# print the arrays and their data types
print(arr1, arr1.dtype)
print(arr2, arr2.dtype)
print(arr3, arr3.dtype)
print(arr4, arr4.dtype)




[dtype('int64')]
float64
complex128
<U5
[b'2' b'4' b'6' b'8'] |S1
[1 2 6] uint16
[1.4 2.5 3.8] float32
[1.+8.j 2.+3.j 3.+5.j] complex64


In [ ]:
# converting data types on existing arrays

#convert data type float to integer

arr1 = np.array([3.1, 2.1, 4.4])

newarr1 = arr.astype('i')

print(newarr1)
print(newarr1.dtype)

# change data type from float to integer
arr5 = np.array([1.2,1.3,1.4,1.5], dtype='I')
print(arr5, arr5.dtype)

# change data type from integer to boolean
arr6 = np.array([1,2,3,4], dtype='bool')
print(arr6, arr6.dtype)

[1 2 3 4 5 6]
int32
[1 1 1 1] uint32
[ True  True  True  True] bool


In [ ]:
# make a copy of an array
arr = np.array([1,2,3,4])
a = arr.copy()
print(a)
#make changes to array
arr[1] = 10
print(arr)
print(a)

# To view the array
b= arr.view()
print(b)

#To check if an array owns its data or not

a = arr.copy()
b = arr.view()
print(a.base)
print(b.base)

[1 2 3 4]
[ 1 10  3  4]
[1 2 3 4]
[ 1 10  3  4]
None
[ 1 10  3  4]


In [ ]:
# To get the shape of an array

arr1 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr1.shape)

arr2 = np.array([1,2,3])
print(arr2.shape)

arr3 = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print(arr3.shape)

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

(2, 4)
(3,)
(2, 2, 4)
[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [ ]:
# Reshaping arrays
# Convert 1-D array to 2-D array
arr1 = np.array([1,2,3,4,5,6,7,8,9])
newarr = arr1.reshape(3,3)
print(newarr)

#convert 1-D array to 3-D array
arr2 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr2 = arr2.reshape(2,3,2)
print(newarr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [3]:
# Flattening numpy arrays
# convert 2-D array into 1-D
arr1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
newarr = arr1.reshape(-1)
print(newarr)


[1 2 3 4 5 6 7 8]


In [8]:
# iterating arrays
# iterate on the 1-D array
arr = np.array([1,2,3,4])

for x in arr:
  print(x)

# iterate on the elements of the 2-D array

arr1 = np.array([[1,2,3,4],[5,6,7,8]])
for x in arr1:
  print(x)
# To get the actual values reiterate on the scalar elements
arr2 = np.array([[[1, 2, 3], [4, 5, 6]]])

for x in arr2:
   for y in x:
       print(y)
# iterate on the 3-D elements
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr3:
   print(x)

# iterating arrays using nditer
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)


1
2
3
4
[1 2 3 4]
[5 6 7 8]
[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
1
2
3
4
5
6
7
8
